export type SupabaseStatusEnv = Record<string, string>;

export function parseSupabaseStatusEnv(output: string): SupabaseStatusEnv {
  return output
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .reduce<SupabaseStatusEnv>((accumulator, line) => {
      const separatorIndex = line.indexOf('=');
      if (separatorIndex <= 0) {
        return accumulator;
      }

      const key = line.slice(0, separatorIndex).trim();
      const value = line.slice(separatorIndex + 1).trim();
      accumulator[key] = value;
      return accumulator;
    }, {});
}

export function buildSupabaseLocalEnvFile(env: SupabaseStatusEnv): string {
  const orderedKeys = [
    'NEXT_PUBLIC_SUPABASE_URL',
    'NEXT_PUBLIC_SUPABASE_ANON_KEY',
    'SUPABASE_URL',
    'SUPABASE_ANON_KEY',
    'SUPABASE_SERVICE_ROLE_KEY'
  ].filter((key) => env[key]);

  return ['# Auto-generated by NeoPages. Commit nothing from this file.', ...orderedKeys.map((key) => `${key}=${env[key]}`), ''].join('\n');
}
