import { describe, expect, it } from 'vitest';

import { buildSupabaseLocalEnvFile, parseSupabaseStatusEnv } from '../index';

describe('parseSupabaseStatusEnv', () => {
  it('parses env-style status output into key-value pairs', () => {
    const env = parseSupabaseStatusEnv([
      'NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321',
      'NEXT_PUBLIC_SUPABASE_ANON_KEY=anon-key',
      'SUPABASE_SERVICE_ROLE_KEY=service-role-key'
    ].join('\n'));

    expect(env.NEXT_PUBLIC_SUPABASE_URL).toBe('http://127.0.0.1:54321');
    expect(env.NEXT_PUBLIC_SUPABASE_ANON_KEY).toBe('anon-key');
    expect(env.SUPABASE_SERVICE_ROLE_KEY).toBe('service-role-key');
  });
});

describe('buildSupabaseLocalEnvFile', () => {
  it('emits a stable env file with the derived local values', () => {
    const contents = buildSupabaseLocalEnvFile({
      NEXT_PUBLIC_SUPABASE_URL: 'http://127.0.0.1:54321',
      NEXT_PUBLIC_SUPABASE_ANON_KEY: 'anon-key',
      SUPABASE_SERVICE_ROLE_KEY: 'service-role-key',
      SUPABASE_URL: 'http://127.0.0.1:54321',
      SUPABASE_ANON_KEY: 'anon-key'
    });

    expect(contents).toContain('# Auto-generated by NeoPages');
    expect(contents).toContain('NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321');
    expect(contents).toContain('SUPABASE_SERVICE_ROLE_KEY=service-role-key');
  });
});
