name = "neopages-gateway"
main = "src/index.ts"
compatibility_date = "2026-03-06"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
account_id = "bf0d7e814f69945157f30505e9fba9fe"

[vars]
ROOT_DOMAIN = "neopages.dev"
DASHBOARD_ORIGIN = "https://neo-pages.vercel.app"
NEOFS_GATEWAY_ORIGIN = "http://http.fs.neo.org/gw"
SUPABASE_URL = "https://jkemmcbseqabvkdtmugq.supabase.co"
CACHE_TTL_SECONDS = "3600"
